### ISSUE TITLE
임산부 데이터 (csv/pdf) 업로드 및 documents

### ISSUE THREAD

**Issue by hanhee-cho** [pladata-encore/DA36-mini4-app1#11]
## 🌈 Success criteria
- 임산부 위험 약물 csv 파일 데이터 정리 >> document
- 임산부 약물 복용 pdf 파일 (3개) 정리 >> document

## 👷 To-do
- [x] csv 파일 로드
 - ` from langchain_community.document_loaders import CSVLoader ` >> list
 - ` pregnancy_csv_docs `

- [x] pdf 파일 로드
 - ` from langchain_community.document_loaders import PyPDFLoader ` >> ` RecursiveCharacterTextSplitter `
 - ` pregnancy_text_docs `

- [x] 단일 documents로 병합
 
## 🧶 Review
